export default function AiGeneratedBadge() {
  return (
    <span
      className="ai-generated-badge"
      title="This content was generated with AI assistance"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="12"
        height="12"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        style={{ marginRight: "0.25rem", verticalAlign: "middle" }}
      >
        <path d="M12 2a4 4 0 0 1 4 4c0 2-2 4-4 6-2-2-4-4-4-6a4 4 0 0 1 4-4z" />
        <path d="M12 22v-4" />
        <path d="M8 18h8" />
      </svg>
      Generated by AI
    </span>
  );
}
