import { describe, it, expect } from "vitest";

describe("POST /api/blog/posts", () => {
  it("requires authentication", async () => {
    const res = await fetch("http://localhost:4321/api/blog/posts", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ title: "Test", body: "Content" }),
    });
    expect(res.status).toBe(401);
  });

  it("rejects missing required fields", async () => {
    const res = await fetch("http://localhost:4321/api/blog/posts", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({}),
    });
    expect(res.status).toBe(400);
    const body = await res.json();
    expect(body).toHaveProperty("error");
  });

  it("rejects title exceeding 200 characters", async () => {
    const res = await fetch("http://localhost:4321/api/blog/posts", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ title: "x".repeat(201), body: "Content" }),
    });
    expect(res.status).toBe(400);
  });

  it("rejects body exceeding 100000 characters", async () => {
    const res = await fetch("http://localhost:4321/api/blog/posts", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ title: "Valid Title", body: "x".repeat(100001) }),
    });
    expect(res.status).toBe(400);
  });

  it("accepts ai_generated flag and creates draft", async () => {
    const res = await fetch("http://localhost:4321/api/blog/posts", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        title: "AI Generated Post",
        body: "Content generated by AI",
        ai_generated: true,
      }),
    });
    expect(res.status).toBe(401);
  });
});
