import { describe, it, expect, vi, afterEach } from "vitest";
import { NextRequest } from "next/server";

const mockGetUser = vi.hoisted(() => vi.fn());
const mockCreateBlogPost = vi.hoisted(() => vi.fn());

vi.mock("@/lib/supabase/server", () => ({
  getUser: mockGetUser,
  supabaseServer: vi.fn(),
}));

vi.mock("@/lib/blog/service", () => ({
  createBlogPost: mockCreateBlogPost,
  listBlogPosts: vi.fn(),
  getBlogPostBySlug: vi.fn(),
}));

describe("POST /api/blog/posts", () => {
  afterEach(() => vi.clearAllMocks());

  it("requires authentication", async () => {
    mockGetUser.mockResolvedValue(null);
    const { POST } = await import("@/app/api/blog/posts/route");
    const req = new NextRequest("http://localhost/api/blog/posts", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ title: "Test", body: "Content" }),
    });
    const res = await POST(req);
    expect(res.status).toBe(401);
  });

  it("rejects missing required fields", async () => {
    mockGetUser.mockResolvedValue({ id: "user-1" });
    mockCreateBlogPost.mockResolvedValue({ success: false, errors: [{ field: "title", message: "Title is required" }] });
    const { POST } = await import("@/app/api/blog/posts/route");
    const req = new NextRequest("http://localhost/api/blog/posts", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({}),
    });
    const res = await POST(req);
    expect(res.status).toBe(400);
    const body = await res.json();
    expect(body).toHaveProperty("error");
  });

  it("rejects title exceeding 200 characters", async () => {
    mockGetUser.mockResolvedValue({ id: "user-1" });
    mockCreateBlogPost.mockResolvedValue({ success: false, errors: [{ field: "title", message: "Title too long" }] });
    const { POST } = await import("@/app/api/blog/posts/route");
    const req = new NextRequest("http://localhost/api/blog/posts", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ title: "x".repeat(201), body: "Content" }),
    });
    const res = await POST(req);
    expect(res.status).toBe(400);
  });

  it("rejects body exceeding 100000 characters", async () => {
    mockGetUser.mockResolvedValue({ id: "user-1" });
    mockCreateBlogPost.mockResolvedValue({ success: false, errors: [{ field: "body", message: "Body too long" }] });
    const { POST } = await import("@/app/api/blog/posts/route");
    const req = new NextRequest("http://localhost/api/blog/posts", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ title: "Valid Title", body: "x".repeat(100001) }),
    });
    const res = await POST(req);
    expect(res.status).toBe(400);
  });

  it("accepts ai_generated flag and creates draft", async () => {
    mockGetUser.mockResolvedValue({ id: "user-1" });
    mockCreateBlogPost.mockResolvedValue({ success: true, post: { id: "new-id", slug: "ai-post", title: "AI Generated Post", status: "draft" } });
    const { POST } = await import("@/app/api/blog/posts/route");
    const req = new NextRequest("http://localhost/api/blog/posts", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ title: "AI Generated Post", body: "Content generated by AI", ai_generated: true }),
    });
    const res = await POST(req);
    expect(res.status).toBe(201);
  });
});
